apiVersion: v1
kind: Service
metadata:
  name: {{ include "ana-automation-ui.fullname" . }}
  labels:
    {{- include "ana-automation-ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "ana-automation-ui.selectorLabels" . | nindent 4 }}
